vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        events:
            uri_prefix: /images/events
            upload_destination: '%kernel.project_dir%/public/images/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
